### ISSUE TITLE
How this repo related with Magisk embedded one?

### ISSUE THREAD

**Issue by AlessandroChecco** [gloeyisk/SystemlessHosts#2]
Hi,

I see that Magisk comes with an embedded systemless-hosts module. That version is 1.0.
Is this one different?

Thanks!

**Comment by gloeyisk** [comment]
> Hi,
> 
> I see that Magisk comes with an embedded systemless-hosts module. That version is 1.0. Is this one different?
> 
> Thanks!

Yes, both modules are different.
The one from Magisk app, is just a placeholder module for those who wants to use 3rd-parties (in this case AdAway) while mine is a on-the-go hosts module for blocking ads (flash and profit).
