### ISSUE TITLE
[Bug] The module seems to be broken on Android 14

### ISSUE THREAD

**Issue by mast3rz3ro** [gloeyisk/SystemlessHosts#3]
Hi there,

I'm running the latest version of the module + AdWay app, however after applying and rebooting the module seems to be not working!

Is this issue could be resolved or it's magisk's related [issue](https://github.com/topjohnwu/Magisk/issues/6738)?

**Comment by gloeyisk** [comment]
> AdWay app


You don't need to use AdAway app anymore when you install/use my module.
